# Generated by Django 3.2.8 on 2021-10-08 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdetails',
            name='mother_tongue',
            field=models.CharField(choices=[('Bengali', 'Bengali'), ('Gujarati', 'Gujarati'), ('Hindi', 'Hindi'), ('Kannada', 'Kannada'), ('Malayalam', 'Malayalam'), ('Marathi', 'Marathi'), ('Marwari', 'Marwari'), ('Oriya', 'Oriya'), ('Punjabi', 'Punjabi'), ('Sindhi', 'Sindhi'), ('Tamil', 'Tamil'), ('Telugu', 'Telugu'), ('Urdu', 'Urdu'), ('Angika', 'Angika'), ('Arunachali', 'Arunachali'), ('Assamese', 'Assamese'), ('Awadhi', 'Awadhi'), ('Bhojpuri', 'Bhojpuri'), ('Brij', 'Brij'), ('Bihari', 'Bihari'), ('Badaga', 'Badaga'), ('Chatisgarhi', 'Chatisgarhi'), ('Dogri', 'Dogri'), ('English', 'English'), ('French', 'French'), ('Garhwali', 'Garhwali'), ('Garo', 'Garo'), ('Haryanvi', 'Haryanvi'), ('Himachali/Pahari', 'Himachali/Pahari'), ('Kanauji', 'Kanauji'), ('Kashmiri', 'Kashmiri'), ('Khandesi', 'Khandesi'), ('Khasi', 'Khasi'), ('Konkani', 'Konkani'), ('Koshali', 'Koshali'), ('Kumaoni', 'Kumaoni'), ('Kutchi', 'Kutchi'), ('Lepcha', 'Lepcha'), ('Ladacki', 'Ladacki'), ('Magahi', 'Magahi'), ('Maithili', 'Maithili'), ('Manipuri', 'Manipuri'), ('Miji', 'Miji'), ('Mizo', 'Mizo'), ('Monpa', 'Monpa'), ('Nicobarese', 'Nicobarese'), ('Nepali', 'Nepali'), ('Rajasthani', 'Rajasthani'), ('Sanskrit', 'Sanskrit'), ('Santhali', 'Santhali'), ('Sourashtra', 'Sourashtra'), ('Tripuri', 'Tripuri'), ('Tulu', 'Tulu'), ('Bagri Rajasthani', 'Bagri Rajasthani'), ('Dhundhari/Jaipuri', 'Dhundhari/Jaipuri'), ('Gujari/Gojari', 'Gujari/Gojari'), ('Harauti', 'Harauti'), ('Lambadi', 'Lambadi'), ('Malvi', 'Malvi'), ('Mewari', 'Mewari'), ('Mewati/Ahirwati', 'Mewati/Ahirwati'), ('Nimadi', 'Nimadi'), ('Shekhawati', 'Shekhawati'), ('Wagdi', 'Wagdi')], max_length=100),
        ),
        migrations.AlterField(
            model_name='basicdetails',
            name='religion',
            field=models.CharField(choices=[('Hindu', 'Hindu'), ('Muslim-All', 'Muslim-All'), ('Muslim-Shia', 'Muslim-Shia'), ('Muslim-Sunni', 'Muslim-Sunni'), ('Muslim-Others', 'Muslim-Others'), ('Christian', 'Christian'), ('Sikh', 'Sikh'), ('Jain-All', 'Jain-All'), ('Jain-Digambar', 'Jain-Digambar'), ('Jain-Shwetambar', 'Jain-Shwetambar'), ('Jain-Others', 'Jain-Others'), ('Parsi', 'Parsi'), ('Buddhist', 'Buddhist'), ('Jewish', 'Jewish'), ('Inter-Religion', 'Inter-Religion')], max_length=200),
        ),
    ]
