# Generated by Django 3.2.8 on 2021-10-08 08:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211008_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='any_disability',
            field=models.CharField(choices=[('Select Options', 'Select Options'), ('None', 'None'), ('Physically Challenged', 'Physically Challenged')], max_length=100),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='family_status',
            field=models.CharField(choices=[('Select Options', 'Select Options'), ('Middle Class', 'Middle Class'), ('Affluent', 'Affluent'), ('Upper Middle Class', 'Upper Middle Class'), ('Rich', 'Rich')], max_length=100),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='family_type',
            field=models.CharField(choices=[('Select Options', 'Select Options'), ('Joint', 'Joint'), ('Nuclear', 'Nuclear')], max_length=100),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='family_value',
            field=models.CharField(choices=[('Select Options', 'Select Options'), ('Orthodox', 'Orthodox'), ('Traditional', 'Traditional'), ('Moderate', 'Moderate'), ('Liberal', 'Liberal')], max_length=100),
        ),
        migrations.AlterField(
            model_name='personaldetails',
            name='marital_status',
            field=models.CharField(choices=[('Select Options', 'Select Options'), ('Never Married', 'Never Married'), ('Widowed', 'Widowed'), ('Divorced', 'Divorced'), ('Awaiting Divorce', 'Awaiting Divorce')], max_length=100),
        ),
        migrations.CreateModel(
            name='ProfessionalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education', models.CharField(choices=[('Select Options', 'Select Options'), ('Aeronautical Engineering', 'Aeronautical Engineering'), ('B.Arch', 'B.Arch'), ('BCA', 'BCA'), ('B.E', 'B.E'), ('B.Plan', 'B.Plan'), ('B.Sc IT/Computer Science', 'B.Sc IT/Computer Science'), ('B.Tech', 'B.Tech'), ('Other Bacherlor Degree in Engineering/Computers', 'Other Bacherlor Degree in Engineering/Computers'), ('B.S(Engineering)', 'B.S(Engineering)'), ('M.Arch', 'M.Arch'), ('MCA', 'MCA'), ('ME', 'ME'), ('M.Sc IT/Computer Science', 'M.Sc IT/Computer Science'), ('M.S(Engg)', 'M.S(Engg)'), ('M.Tech', 'M.Tech'), ('PGDCA', 'PGDCA'), ('Other Master Degree in Engineering/Computer', 'Other Master Degree in Engineering/Computer'), ('B.A', 'B.A'), ('B.Com', 'B.Com'), ('B.Ed', 'B.Ed'), ('BFA', 'BFA'), ('BFT', 'BFT'), ('BLIS', 'BLIS'), ('B.M.M', 'B.M.M'), ('B.Sc', 'B.Sc'), ('B.S.W', 'B.S.W'), ('B.Phil', 'B.Phil'), ('M.A', 'M.A'), ('M.Sc', 'M.Sc'), ('BBA', 'BBA'), ('MBA', 'MBA'), ('Software Engineer', 'Software Engineer')], max_length=1000)),
                ('employed_in', models.CharField(choices=[('Government/PSU', 'Government/PSU'), ('Private', 'Private'), ('Business', 'Business'), ('Defence', 'Defence'), ('Self Employed', 'Self Employed'), ('Not Working', 'Not Working')], max_length=100)),
                ('occupation', models.CharField(choices=[('Software Professional', 'Software Professional'), ('Teaching', 'Teaching'), ('Executive', 'Executive'), ('Doctor', 'Doctor'), ('Manager', 'Manager'), ('Professor/Lecturer', 'Professor/Lecturer'), ('Officer', 'Officer'), ('Human Resources Professional', 'Human Resources Professional'), ('Pilot', 'Pilot'), ('Air Hostess', 'Air Hostess'), ('Chartered Accountant', 'Chartered Accountant'), ('Fashion Designer', 'Fashion Designer'), ('MakeUp Artist', 'MakeUp Artist'), ('Civil Services(IAS/IPS/IRS)', 'Civil Services(IAS/IPS/IRS)')], max_length=100)),
                ('annual_income', models.CharField(choices=[('0-1Lakhs', '0-1Lakhs'), ('1-2lakhs', '1-2lakhs'), ('2-3lakhs', '2-3lakhs'), ('3-4lakhs', '3-4lakhs'), ('4-5lakhs', '4-5lakhs'), ('5-6lakhs', '5-6lakhs'), ('6-7lakhs', '6-7lakhs'), ('7-8lakhs', '7-8lakhs'), ('8-9lakhs', '8-9lakhs'), ('9-10lakhs', '9-10lakhs'), ('10-12lakhs', '10-12lakhs'), ('12-14lakhs', '12-14lakhs'), ('14-16lakhs', '14-16lakhs'), ('16-18lakhs', '16-18lakhs'), ('18-20lakhs', '18-20lakhs'), ('20-25lakhs', '20-25kakhs'), ('25-30lakhs', '25-30lakhs'), ('30-35lakhs', '30-35lakhs'), ('35-40lakhs', '35-40lakhs'), ('40-45lakhs', '40-45lakhs'), ('45-50lakhs', '45-50lakhs'), ('50-60lakhs', '50-60lakhs'), ('60-70lakhs', '60-70lakhs'), ('70-80lakhs', '70-80lakhs'), ('80-90lakhs', '80-90lakhs'), ('90-1crore', '90-1crore'), ('1crore & Above', '1crore & Above')], max_length=1000)),
                ('work_location', models.CharField(max_length=100)),
                ('residing_state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
