# Generated by Django 3.2.8 on 2021-10-08 09:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20211008_1346'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('membership', models.CharField(choices=[('Silver', 'Silver'), ('Gold', 'Gold'), ('Diamond', 'Diamond')], max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='professionaldetails',
            name='annual_income',
            field=models.CharField(choices=[('Select Options', 'Select Options'), ('0-1Lakhs', '0-1Lakhs'), ('1-2lakhs', '1-2lakhs'), ('2-3lakhs', '2-3lakhs'), ('3-4lakhs', '3-4lakhs'), ('4-5lakhs', '4-5lakhs'), ('5-6lakhs', '5-6lakhs'), ('6-7lakhs', '6-7lakhs'), ('7-8lakhs', '7-8lakhs'), ('8-9lakhs', '8-9lakhs'), ('9-10lakhs', '9-10lakhs'), ('10-12lakhs', '10-12lakhs'), ('12-14lakhs', '12-14lakhs'), ('14-16lakhs', '14-16lakhs'), ('16-18lakhs', '16-18lakhs'), ('18-20lakhs', '18-20lakhs'), ('20-25lakhs', '20-25kakhs'), ('25-30lakhs', '25-30lakhs'), ('30-35lakhs', '30-35lakhs'), ('35-40lakhs', '35-40lakhs'), ('40-45lakhs', '40-45lakhs'), ('45-50lakhs', '45-50lakhs'), ('50-60lakhs', '50-60lakhs'), ('60-70lakhs', '60-70lakhs'), ('70-80lakhs', '70-80lakhs'), ('80-90lakhs', '80-90lakhs'), ('90-1crore', '90-1crore'), ('1crore & Above', '1crore & Above')], max_length=1000),
        ),
        migrations.AlterField(
            model_name='professionaldetails',
            name='employed_in',
            field=models.CharField(choices=[('Select Options', 'Select Options'), ('Government/PSU', 'Government/PSU'), ('Private', 'Private'), ('Business', 'Business'), ('Defence', 'Defence'), ('Self Employed', 'Self Employed'), ('Not Working', 'Not Working')], max_length=100),
        ),
        migrations.AlterField(
            model_name='professionaldetails',
            name='occupation',
            field=models.CharField(choices=[('Select Options', 'Select Options'), ('Software Professional', 'Software Professional'), ('Teaching', 'Teaching'), ('Executive', 'Executive'), ('Doctor', 'Doctor'), ('Manager', 'Manager'), ('Professor/Lecturer', 'Professor/Lecturer'), ('Officer', 'Officer'), ('Human Resources Professional', 'Human Resources Professional'), ('Pilot', 'Pilot'), ('Air Hostess', 'Air Hostess'), ('Chartered Accountant', 'Chartered Accountant'), ('Fashion Designer', 'Fashion Designer'), ('MakeUp Artist', 'MakeUp Artist'), ('Civil Services(IAS/IPS/IRS)', 'Civil Services(IAS/IPS/IRS)')], max_length=100),
        ),
        migrations.AlterField(
            model_name='professionaldetails',
            name='work_location',
            field=models.CharField(choices=[('Select Options', 'Select Options'), ('Indian', 'Indian'), ('United States of America', 'United States of America'), ('United Arab Emirates', 'United Arab Emirates'), ('United Kingdom', 'United Kingdom'), ('Australia', 'Australia'), ('Singapore', 'Singapore'), ('Canada', 'Canada'), ('Qatar', 'Qatar'), ('Kuwait', 'Kuwait'), ('Oman', 'Oman'), ('Bahrain', 'Bahrain'), ('Saudi Arabia', 'Saudi Arabia'), ('Malaysia', 'Malaysia')], max_length=100),
        ),
        migrations.CreateModel(
            name='PaymentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('payment_signature', models.CharField(blank=True, max_length=100, null=True)),
                ('is_paid', models.BooleanField(default=False)),
                ('package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.package')),
                ('register', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
