# Generated by Django 3.2.8 on 2021-10-08 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20211008_1456'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PaymentDetail',
            new_name='PaymentDetails',
        ),
        migrations.AlterField(
            model_name='package',
            name='membership',
            field=models.CharField(choices=[('Select Options', 'Select Options'), ('Silver', 'Silver'), ('Gold', 'Gold'), ('Diamond', 'Diamond')], max_length=100),
        ),
    ]
