# Generated by Django 3.2.8 on 2021-10-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20211009_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professionaldetails',
            name='work_location',
            field=models.CharField(choices=[('Select Options', 'Select Options'), ('Indian', 'Indian')], max_length=100),
        ),
    ]
