# Generated by Django 3.2.8 on 2021-10-09 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_professionaldetails_work_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='mobile_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
